AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Micronaut AWS Lambda Application

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: The environment to deploy to

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java21
    Architectures:
      - x86_64
    Environment:
      Variables:
        MICRONAUT_ENVIRONMENTS: !Ref Environment

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${AWS::StackName}-api'
      StageName: !Ref Environment
  CustomAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.miccab.installation.flow.api.authorizer.SimpleAuthorizer
      CodeUri: target/installation-flow-api-1.0-SNAPSHOT.jar
      Policies:
        - AWSLambdaBasicExecutionRole
  MicronautLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyRequestEventFunction
      CodeUri: target/installation-flow-api-1.0-SNAPSHOT.jar
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvents:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY
            Authorizer:
              FunctionArn: !GetAtt CustomAuthorizerFunction.Arn
              Identity:
                Header: Authorization

Outputs:
  HttpApi:
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
