AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Micronaut AWS Lambda Application

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: The environment to deploy to

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java21
    Architectures:
      - x86_64
    Environment:
      Variables:
        MICRONAUT_ENVIRONMENTS: !Ref Environment

Resources:
  MicronautLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.micronaut.function.aws.MicronautRequestStreamHandler
      CodeUri: target/
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvents:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  HttpApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
