name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v3.1.2
        with:
          step: restore
      - name: Build with Maven
        run: mvn -B package
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v3.1.2
        with:
          step: save
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: SAM Deploy
        run: sam deploy --s3-bucket installation-flow-api-bucket-${{ vars.ENVIRONMENT }} --stack-name installation-flow-api-${{ vars.ENVIRONMENT }} --capabilities CAPABILITY_IAM --parameter-overrides Environment=${{ vars.ENVIRONMENT }} --no-fail-on-empty-changeset --no-confirm-changeset --force-upload

